import { StyleSheet } from "react-native";
import { MODULE_COLOR } from "../utils/sharedUI";

export const createChartStyles = (
  theme: any,
  isDark: boolean,
  primaryTextColor: string,
  secondaryTextColor: string
) =>
  StyleSheet.create({
    container: { flex: 1 },

    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.spacing.screenPadding,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.sm,
    },
    headerTitle: {
      fontSize: theme.typography.fontSizes.xl,
      fontWeight: theme.typography.fontWeights.bold,
      color: theme.colors.textPrimary,
    },
    headerRight: { flexDirection: "row", alignItems: "center" },

    contentWrapper: {
      flex: 1,
      paddingHorizontal: theme.spacing.screenPadding,
      paddingTop: 10,
    },
    contentContainer: { paddingBottom: 140, flexGrow: 1 },

    centerWrapper: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyText: {
      marginTop: 8,
      fontSize: 13,
      color: secondaryTextColor,
      textAlign: "center",
    },

    heroWrapper: { alignItems: "center", marginTop: 12, marginBottom: 18 },
    heroOrbOuter: {
      width: 120,
      height: 120,
      borderRadius: 60,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: theme.spacing.md,
      backgroundColor: `${MODULE_COLOR}10`,
      shadowColor: MODULE_COLOR,
      shadowOpacity: isDark ? 0.7 : 0.3,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 12,
    },
    heroTitleText: {
      marginTop: 2,
      fontSize: theme.typography.fontSizes.xl,
      fontWeight: "700",
      color: theme.colors.textPrimary,
    },
    heroSubtitleText: {
      marginTop: 4,
      fontSize: 12,
      textAlign: "center",
      color: theme.colors.textSecondary,
    },

    yearRowLabel: {
      marginTop: 4,
      marginLeft: 4,
      marginBottom: 4,
      fontSize: 12,
      color: theme.colors.textPrimary,
    },
    yearFilterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 8,
    },
    yearChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      marginRight: 8,
      marginTop: 6,
      backgroundColor: isDark ? "#020617" : "#F1F5F9",
      borderColor: isDark ? "#1F2937" : "#CBD5E1",
    },
    yearChipActive: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      marginRight: 8,
      marginTop: 6,
      backgroundColor: isDark ? "#082F49" : "#DBEAFE",
      borderColor: MODULE_COLOR,
    },
    yearChipText: {
      fontSize: 13,
      fontWeight: "500",
      color: secondaryTextColor,
    },
    yearChipTextActive: {
      fontSize: 13,
      fontWeight: "600",
      color: MODULE_COLOR,
    },

    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 4,
    },
    summaryBox: {
      flex: 1,
      marginHorizontal: 4,
      borderRadius: 14,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: isDark ? "#020617" : "#E0F2FE",
      borderWidth: 1,
      borderColor: isDark ? "#1E3A8A" : "#93C5FD",
      position: "relative",
      overflow: "hidden",
    },
    summaryLabel: { fontSize: 11, color: secondaryTextColor },
    summaryValue: {
      marginTop: 2,
      fontSize: 18,
      fontWeight: "700",
      color: primaryTextColor,
    },
    summarySub: { marginTop: 2, fontSize: 11, color: secondaryTextColor },
    neonBottomLine: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      height: 3,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
    },

    segmentRow: {
      flexDirection: "row",
      borderRadius: 20,
      backgroundColor: isDark ? "#020617" : "#E5E7EB",
      padding: 5,
      marginTop: 20,
      marginBottom: 16,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    segmentButtonActive: {
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 4,
    },
    segmentButtonText: {
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: 0.2,
      color: isDark ? "#9CA3AF" : "#6B7280",
    },
    segmentButtonTextActive: {
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: 0.2,
      color: "#0F172A",
    },

    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 8,
      marginBottom: 8,
    },
    sectionHeaderIconWrapper: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 8,
      backgroundColor: `${MODULE_COLOR}20`,
    },
    sectionHeaderText: {
      fontSize: 14,
      fontWeight: "700",
      color: theme.colors.textPrimary,
      letterSpacing: 0.2,
    },

    chartCard: {
      borderRadius: 18,
      paddingVertical: 16,
      paddingHorizontal: 16,
      marginTop: 12,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: isDark ? "#1F2937" : "#E5E7EB",
      shadowColor: MODULE_COLOR,
      shadowOpacity: isDark ? 0.3 : 0.2,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 6 },
      elevation: 8,
    },
    titleText: {
      textAlign: "center",
      marginBottom: 6,
      fontSize: 17,
      fontWeight: "700",
      color: theme.colors.textPrimary,
      letterSpacing: 0.2,
    },
    subtitleText: {
      textAlign: "center",
      marginBottom: 12,
      fontSize: 12,
      color: secondaryTextColor,
      lineHeight: 16,
    },

    legendRow: {
      flexDirection: "row",
      justifyContent: "center",
      marginTop: 4,
    },
    legendItem: {
      flexDirection: "row",
      alignItems: "center",
      marginHorizontal: 8,
    },
    legendDotTasks: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginRight: 4,
      backgroundColor: "rgba(56, 189, 248, 1)",
    },
    legendDotEvents: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginRight: 4,
      backgroundColor: "rgba(34, 197, 94, 1)",
    },
    legendLabel: { fontSize: 11, color: secondaryTextColor },

    insightsCard: {
      marginTop: 16,
      borderRadius: 18,
      paddingVertical: 16,
      paddingHorizontal: 16,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: isDark ? "#1F2937" : "#E5E7EB",
      shadowColor: MODULE_COLOR,
      shadowOpacity: isDark ? 0.25 : 0.15,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
    insightsTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    insightsTitleText: {
      marginLeft: 8,
      fontSize: 17,
      fontWeight: "700",
      color: theme.colors.textPrimary,
      letterSpacing: 0.2,
    },
    insightsHintText: {
      fontSize: 12,
      color: secondaryTextColor,
      marginBottom: 12,
      lineHeight: 16,
    },
    bulletRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginTop: 8,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: MODULE_COLOR,
      marginRight: 10,
      marginTop: 5,
    },
    bulletText: {
      fontSize: 13,
      color: theme.colors.textPrimary,
      flex: 1,
      lineHeight: 20,
    },
  });
