import { StyleSheet } from "react-native";

export const createTaskFormStyles = (theme: any, MODULE_COLOR: string) =>
  StyleSheet.create({
    sectionCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: MODULE_COLOR,
      shadowOpacity: theme.isDark ? 0.3 : 0.15,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    sectionIcon: {
      marginRight: 10,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.colors.textPrimary,
      letterSpacing: 0.3,
    },
    label: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.textSecondary,
      marginBottom: 8,
      letterSpacing: 0.2,
    },
    inputContainer: {
      borderRadius: 12,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: MODULE_COLOR,
      shadowOpacity: theme.isDark ? 0.25 : 0.15,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    dateButton: {
      padding: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 12,
      backgroundColor: theme.colors.card,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      shadowColor: MODULE_COLOR,
      shadowOpacity: theme.isDark ? 0.25 : 0.15,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    dateButtonText: {
      fontSize: 14,
      fontWeight: "500",
    },
    chipContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 8,
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: theme.isDark ? "#1F2937" : "#DBEAFE",
      borderWidth: 1,
      borderColor: theme.isDark ? "#374151" : "#93C5FD",
      marginRight: 8,
      marginBottom: 8,
    },
    chipText: {
      fontSize: 12,
      fontWeight: "500",
      color: theme.colors.textPrimary,
      marginLeft: 6,
    },
    chipClose: {
      marginLeft: 8,
    },
    addInputRow: {
      flexDirection: "row",
      marginTop: 12,
      alignItems: "center",
    },
    addInputContainer: {
      flex: 1,
      marginRight: 10,
    },
    submitButton: {
      marginTop: 10,
      borderRadius: 12,
      shadowColor: MODULE_COLOR,
      shadowOpacity: theme.isDark ? 0.4 : 0.3,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
  });
